/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iplayer_mine_util_NativeHelper */

#ifndef _Included_com_iplayer_mine_util_NativeHelper
#define _Included_com_iplayer_mine_util_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iplayer_mine_util_NativeHelper
 * Method:    blurBitmap
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_iplayer_mine_util_NativeHelper_blurBitmap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
